import type { TranslationDictionary } from "@/i18n/types";

export const experienceTranslations: TranslationDictionary = {
  experience_cr_espassos_name: {
    en: "Architect",
    pt: "Arquiteto",
    es: "Arquitecto",
  },
  experience_cr_espassos_description: {
    en: "At CR Espassos, I worked as an Architect in a multidisciplinary team, contributing to projects across architecture, engineering, and interior design. This experience required adapting to different types of requirements and collaborating closely with professionals from multiple areas to deliver cohesive solutions. I also took on a leadership role by mentoring junior team members, assigning tasks, and supporting their day-to-day work and development. This experience helped shape my approach to problem-solving, structure, and design, which I later brought into my work as a developer.",
    pt: "Na CR Espassos, trabalhei como arquiteto numa equipa multidisciplinar, contribuindo para projetos nas áreas de arquitetura, engenharia e design de interiores. Esta experiência exigiu adaptação a diferentes tipos de requisitos e colaboração próxima com profissionais de várias áreas para entregar soluções coerentes. Assumi também um papel de liderança ao orientar membros mais juniores, atribuindo tarefas e apoiando o seu trabalho e desenvolvimento no dia a dia. Esta experiência influenciou a forma como abordo problemas, estrutura e design, algo que mais tarde trouxe para o desenvolvimento de software.",
    es: "En CR Espassos, trabajé como arquitecto en un equipo multidisciplinar, contribuyendo a proyectos en las áreas de arquitectura, ingeniería y diseño de interiores. Esta experiencia requirió adaptarme a distintos tipos de requisitos y colaborar estrechamente con profesionales de diferentes áreas para ofrecer soluciones coherentes. También asumí un rol de liderazgo, guiando a miembros junior, asignando tareas y apoyando su trabajo y desarrollo diario. Esta experiencia influyó en mi forma de abordar problemas, la estructura y el diseño, algo que posteriormente apliqué en el desarrollo de software.",
  },
  experience_subvisual_description: {
    en: "At Subvisual, I worked as a Full-Stack Developer in an apprenticeship program, contributing to both web2 and web3 projects in a collaborative environment. During this experience, I developed a full-stack internal platform focused on team and skill management, as well as a web3 application integrating frontend development with smart contracts. This role allowed me to work closely with experienced developers and gain hands-on experience in a production-like environment, contributing across the stack with a stronger focus on frontend.",
    pt: "Na Subvisual, trabalhei como Full-Stack Developer num programa de aprendizagem, contribuindo para projetos web2 e web3 num ambiente colaborativo. Durante esta experiência, desenvolvi uma plataforma interna full-stack focada na gestão de equipas e competências, bem como uma aplicação web3 que integrava desenvolvimento frontend com smart contracts. Esta experiência permitiu-me trabalhar de perto com developers experientes e ganhar experiência prática num ambiente próximo de produção, contribuindo em várias áreas do stack, com maior foco em frontend.",
    es: "En Subvisual, trabajé como Full-Stack Developer en un programa de aprendizaje, contribuyendo a proyectos web2 y web3 en un entorno colaborativo. Durante esta experiencia, desarrollé una plataforma interna full-stack centrada en la gestión de equipos y habilidades, así como una aplicación web3 que integraba desarrollo frontend con smart contracts. Este rol me permitió trabajar de cerca con desarrolladores experimentados y adquirir experiencia práctica en un entorno similar a producción, contribuyendo en diferentes áreas del stack, con mayor enfoque en frontend.",
  },
  experience_talent_protocol_description: {
    en: "At Talent Protocol, I worked as a Frontend Developer across multiple products in a web3 ecosystem, contributing mainly to frontend development. I was responsible for building the Build.top frontend from scratch, translating Figma designs into a fully functional application. I also contributed to other core products, including Talent Passport, implementing features, improving UI/UX, and addressing user feedback. Throughout this experience, I worked on maintaining and extending a shared design system, ensuring consistency across different applications. This role exposed me to a fast-paced environment where iteration, product feedback, and continuous improvement were central to the development process.",
    pt: "Na Talent Protocol, trabalhei como Frontend Developer em vários produtos dentro de um ecossistema web3, com foco principal no desenvolvimento frontend. Fui responsável por desenvolver o frontend da Build.top de raiz, traduzindo designs em Figma numa aplicação totalmente funcional. Também contribuí para outros produtos principais, como o Talent Passport, implementando novas funcionalidades, melhorando a UI/UX e respondendo ao feedback dos utilizadores. Durante esta experiência, trabalhei na manutenção e evolução de um design system partilhado, garantindo consistência entre diferentes aplicações. Este papel deu-me experiência num ambiente dinâmico, onde a iteração, o feedback do produto e a melhoria contínua eram fundamentais.",
    es: "En Talent Protocol, trabajé como Frontend Developer en varios productos dentro de un ecosistema web3, con un enfoque principal en el desarrollo frontend. Fui responsable de desarrollar el frontend de Build.top desde cero, traduciendo diseños de Figma en una aplicación completamente funcional. También contribuí a otros productos clave, como Talent Passport, implementando nuevas funcionalidades, mejorando la UI/UX y respondiendo al feedback de los usuarios. Durante esta experiencia, trabajé en el mantenimiento y evolución de un design system compartido, asegurando la consistencia entre diferentes aplicaciones. Este rol me permitió trabajar en un entorno dinámico, donde la iteración, el feedback de producto y la mejora continua eran fundamentales.",
  },
  experience_aquasis_description: {
    en: "At Aquasis, I work as a Frontend Developer on the company's main platform, contributing to the development of new product functionality in a cross-functional team. My work focuses on building scalable frontend features using React, while helping modernize the platform by migrating from a legacy jQuery-based system to a more maintainable React architecture. Given my background in architecture, I also take an active role in UI/UX decisions, translating product requirements into clear, structured, and usable interface designs.",
    pt: "Na Aquasis, trabalho como Frontend Developer na principal plataforma da empresa, contribuindo para o desenvolvimento de novas funcionalidades em colaboração com uma equipa multidisciplinar. O meu trabalho foca-se no desenvolvimento de funcionalidades frontend escaláveis com React, ao mesmo tempo que participo na modernização da plataforma através da migração de um sistema legado baseado em jQuery para uma arquitetura mais moderna e sustentável em React. Com a minha formação em arquitetura, tenho também um papel ativo nas decisões de UI/UX, traduzindo requisitos de produto em interfaces claras, estruturadas e fáceis de utilizar.",
    es: "En Aquasis, trabajo como Frontend Developer en la plataforma principal de la empresa, contribuyendo al desarrollo de nuevas funcionalidades en colaboración con un equipo multidisciplinar. Mi trabajo se centra en el desarrollo de funcionalidades frontend escalables con React, al mismo tiempo que participo en la modernización de la plataforma mediante la migración de un sistema legado basado en jQuery a una arquitectura más moderna y mantenible en React. Gracias a mi formación en arquitectura, también tengo un papel activo en las decisiones de UI/UX, traduciendo los requisitos del producto en interfaces claras, estructuradas y fáciles de usar.",
  },
};
