export const certifications = [
  {
    id: "0",
    type: "certifications",
    name: "Agile Course",
    place: "Udemy",
    description:
      "Explored the most popular Agile Methodologies such as Scrum, Kanban, DSDM, Extreme Programming (XP) and Lean Software Development.",
    link: "https://www.udemy.com/course/agile-project-management-certification/",
    techs: ["Agile Methodologies", "Lean Principles", "Kanban", "Jira"],
    yearStart: "2024",
    monthStart: "Jan",
    yearEnd: null,
    monthEnd: null,
  },
  {
    id: "1",
    type: "certifications",
    name: "React Native Course",
    place: "Udemy",
    dateEnd: null,
    description:
      "React Native course with hands-on experience, building an app from the ground up that explored functional and class components; implemented React Context and Hooks; integrated REST APIs; implemented tab navigation; enabled image uploads; created swipeable carousels and facilitated external actions like email and phone calls.",
    link: "https://www.udemy.com/course/build-mobile-apps-with-react-native-from-to-zero-to-expert/",
    techs: ["React Native", "JavaScript", "REST API", "Postman"],
    yearStart: "2024",
    monthStart: "Jan",
    yearEnd: null,
    monthEnd: null,
  },
  {
    id: "2",
    type: "certifications",
    name: "OutSystems Course",
    place: "Udemy",
    dateEnd: null,
    description:
      "Acquired expertise in OutSystems through End-To-End Reactive Development, mastering basic to advanced features, best coding practices, application architecture design, and enterprise-grade solutions. Learned how to apply advanced UI widgets, delved into intricate database concepts, and seamlessly integrated Web APIs. Developed proficiency in troubleshooting and optimizing performance, ensuring robust functionality. This journey culminated in a comprehensive understanding of the OutSystems ecosystem, empowering me to contribute effectively to the development of projects as an OutSystems Developer.",
    link: "https://www.udemy.com/course/complete-course-on-outsystems-development/",
    techs: ["OutSystems"],
    yearStart: "2024",
    monthStart: "Feb",
    yearEnd: null,
    monthEnd: null,
  },
];
