export const experience = [
  {
    id: "0",
    type: "experience",
    name: "Architect",
    place: "CR espassos",
    description:
      "Worked in a team of architects and engineers as one of the main architects. Had to adapt myself to collaborate in various areas, including engineering, urbanism, and interior design, to meet project requirements. Led and helped a team of third-year internship engineering students",
    link: "https://www.linkedin.com/company/cr-espassos/about/",
    techs: ["Revit", "AutoCAD", "Microsoft Office"],
    yearStart: "2022",
    monthStart: "Sep",
    yearEnd: "2023",
    monthEnd: "Aug",
  },
  {
    id: "1",
    type: "experience",
    name: "Full-stack Developer",
    place: "Talent Protocol",
    description:
      "Millions are wasted every year betting on the wrong talent. Talent Protocol unlocks rich and verifiable reputation data and makes true talent more visible.",
    link: "https://www.talentprotocol.com/",
    techs: [
      "JavaScript",
      "TypeScript",
      "CSS",
      "React",
      "Next.js",
      "Ruby",
      "Ruby on Rails",
      "Supabase",
      "Joy UI",
      "Notion",
    ],
    yearStart: "2024",
    monthStart: "Mar",
    yearEnd: null,
    monthEnd: "Present",
  },
];
