export const projects = [
  {
    id: "0",
    type: "projects",
    name: "Giraffes vs Sea",
    subject: "2D Tower Defense Game",
    description:
      "Towerdefense videogame where the players use math to win. Independently conceived and executed the game.",
    link: "https://giraffes-vs-sea.netlify.app",
    techs: ["HTML", "CSS", "JavaScript", "DOM Manipulation"],
    yearStart: "2023",
    monthStart: "Sep",
    yearEnd: null,
    monthEnd: null,
    img: "../../../01-project.png",
  },
  {
    id: "1",
    type: "projects",
    name: "House of Legends",
    subject: "League of Legends Website",
    description:
      "Designed a League of Legends platform enabling users to explore champion and item details and create personalized builds. Applied CRUD operations and integrated League of Legends API to dynamically create, fetch, update and delete game information. Introduced search and filtering functionalities, elevating the website beyond information retrieval to an interactive platform.",
    link: "https://house-of-legends.netlify.app",
    techs: ["HTML", "CSS", "JavaScript", "React", "Node.js", "REST API"],
    yearStart: "2023",
    monthStart: "Oct",
    yearEnd: null,
    monthEnd: null,
    img: "../../../02-project.png",
  },
  {
    id: "2",
    type: "projects",
    name: "FIN/ACE",
    subject: "Personal Finances Website",
    description:
      "Designed a three-page structure encompassing a dynamic dashboard, insightful overview, and a transaction log, providing users with a comprehensive tool for tracking, planning, and analyzing their incomes and expenses. Implemented user authentication to ensure unique access. Successfully embraced the challenge of incorporating unfamiliar libraries, such as Chart.js, to enhance the visualization of financial data.",
    link: "https://finace.netlify.app",
    techs: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
    ],
    yearStart: "2023",
    monthStart: "Nov",
    yearEnd: null,
    monthEnd: null,
    img: "../../../03-project.png",
  },
  {
    id: "3",
    type: "projects",
    name: "TGDESIGN",
    description: "My personal portfolio",
    techs: ["HTML", "SCSS", "JavaScript", "React"],
    yearStart: "2024",
    monthStart: "Jan",
    yearEnd: null,
    monthEnd: null,
  },
];
