export const projects = [
  {
    id: "0",
    name: "Giraffes vs Sea",
    date: "09/2023",
    img: "project0.jpg",
    description: "This is the description for Project 1.",
    link: "https://giraffes-vs-sea.netlify.app",
    techs: [
      "HTML",
      "CSS",
      "JavaScript",
      "DOM Manipulation",
      "DOM Manipulation",
      "DOM Manipulation",
    ],
  },
  {
    id: "1",
    name: "House of Legends",
    date: "10/2023",
    img: "project1.jpg",
    description: "This is the description for Project 2.",
    link: "https://house-of-legends.netlify.app",
    techs: ["HTML", "CSS", "JavaScript", "React", "Node.js", "REST API"],
  },
  {
    id: "2",
    name: "FIN/ACE",
    date: "11/2023",
    img: "project2.jpg",
    description: "This is the description for Project 3.",
    link: "https://finace.netlify.app",
    techs: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
    ],
  },
  {
    id: "3",
    name: "TGDESIGN",
    date: "01/2024",
    img: "project3.jpg",
    description: "This is the description for Project 0.",
    techs: ["HTML", "CSS", "JavaScript", "React"],
  },
];
