export const projects = [
  {
    id: "0",
    type: "projects",
    name: "Giraffes vs Sea",
    subject: "2D Tower Defense Game",
    description:
      "Towerdefense videogame where the players use math to win. Independently conceived and executed the game.",
    link: "https://giraffes-vs-sea.netlify.app",
    techs: ["HTML", "CSS", "JavaScript", "DOM Manipulation"],
    yearStart: "2023",
    monthStart: "Sep",
    yearEnd: null,
    monthEnd: null,
    img: "../../../01-project.png",
  },
  {
    id: "1",
    type: "projects",
    name: "House of Legends",
    subject: "League of Legends Website",
    description:
      "Web application that gives information about the video game League of Legends, allowing users to create and customize builds.",
    link: "https://house-of-legends.netlify.app",
    techs: ["HTML", "CSS", "JavaScript", "React", "Node.js", "REST API"],
    yearStart: "2023",
    monthStart: "Oct",
    yearEnd: null,
    monthEnd: null,
    img: "../../../02-project.png",
  },
  {
    id: "2",
    type: "projects",
    name: "FIN/ACE",
    subject: "Personal Finances Website",
    link: "https://finace.netlify.app",
    techs: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
    ],
    yearStart: "2023",
    monthStart: "Nov",
    yearEnd: null,
    monthEnd: null,
  },
  {
    id: "3",
    type: "projects",
    name: "Personal website",
    subject: "Personal website",
    link: "https://thetiagogil.netlify.app/",
    techs: ["HTML", "JavaScript", "React", "Joy UI"],
    yearStart: "2024",
    monthStart: "Jan",
    yearEnd: null,
    monthEnd: null,
  },
  {
    id: "4",
    type: "projects",
    name: "FIN/ACE v2",
    subject: "Personal Finances Website",
    description:
      "Web application designed for financial tracking and analysis. It provides users with tools to manage and visualize their income and expenses over different years and months, as well as offering various features to help users understand their financial data through detailed summaries and visual representations.",
    link: "https://finace-v2.netlify.app",
    techs: [
      "HTML",
      "TypeScript",
      "React",
      "Node.js",
      "Express.js",
      "Supabase",
      "Joy UI",
    ],
    yearStart: "2024",
    monthStart: "Jul",
    yearEnd: null,
    monthEnd: null,
    img: "../../../03-project.png",
  },
  {
    id: "5",
    type: "projects",
    name: "FIN/ACE v3",
    subject: "Personal Finances Website",
    description:
      "Web application designed for financial tracking and analysis. It provides users with tools to manage and visualize their income and expenses over different years and months, as well as offering various features to help users understand their financial data through detailed summaries and visual representations.",
    link: "",
    techs: [
      "HTML",
      "TypeScript",
      "React",
      "Node.js",
      "Express.js",
      "Supabase",
      "Joy UI",
    ],
    yearStart: "2024",
    monthStart: "Sep",
    yearEnd: null,
    monthEnd: null,
  },
];
