import type { EducationItem } from "@/types/data";

export const education: EducationItem[] = [
  {
    id: "edu-faul",
    category: "education",
    title: "",
    titleKey: "education_faul_name",
    org: "",
    orgKey: "education_faul_place",
    descriptionKey: "education_faul_description",
    link: "https://www.fa.ulisboa.pt/index.php/en/",
    techs: ["AutoCAD", "SketchUp", "Adobe Photoshop", "Microsoft Office"],
    dateStart: new Date("2014-09-01"),
    dateEnd: new Date("2022-07-31"),
    status: "completed",
    img: "education/faul.jpeg",
    featured: true,
    hasDetailsPage: true,
  },
  {
    id: "edu-ironhack",
    category: "education",
    title: "",
    titleKey: "education_ironhack_name",
    org: "Ironhack",
    descriptionKey: "education_ironhack_description",
    link: "https://www.ironhack.com",
    techs: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST API",
      "DOM Manipulation",
    ],
    dateStart: new Date("2023-08-01"),
    dateEnd: new Date("2023-11-30"),
    status: "completed",
    img: "education/ironhack.jpeg",
    featured: true,
    hasDetailsPage: true,
  },
];
