import type { DataItem } from "@/types/data";

export const education: DataItem[] = [
  {
    id: "edu-guadalupe",
    category: "education",
    title: "",
    titleKey: "education_guadalupe_name",
    org: "Colégio Guadalupe",
    descriptionKey: "education_guadalupe_description",
    link: "https://c-guadalupe.com/en/",
    techs: ["Microsoft Office"],
    dateStart: new Date("2011-09"),
    dateEnd: new Date("2014-07"),
    status: "completed",
    img: "education/cg.jpeg",
    featured: true,
  },
  {
    id: "edu-faul",
    category: "education",
    title: "",
    titleKey: "education_faul_name",
    org: "",
    orgKey: "education_faul_place",
    descriptionKey: "education_faul_description",
    link: "https://www.fa.ulisboa.pt/index.php/en/",
    techs: ["AutoCAD", "SketchUp", "Adobe Photoshop", "Microsoft Office"],
    dateStart: new Date("2014-09"),
    dateEnd: new Date("2022-07"),
    status: "completed",
    img: "education/faul.jpeg",
    featured: true,
  },
  {
    id: "edu-ironhack",
    category: "education",
    title: "",
    titleKey: "education_ironhack_name",
    org: "Ironhack",
    descriptionKey: "education_ironhack_description",
    link: "https://www.ironhack.com",
    techs: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "REST API",
      "DOM Manipulation",
    ],
    dateStart: new Date("2023-08"),
    dateEnd: new Date("2023-11"),
    status: "completed",
    img: "education/ironhack.jpeg",
    featured: true,
  },
];
