import type { DataItem } from "@/types/data";

export const experience: DataItem[] = [
  {
    id: "exp-crespassos",
    category: "experience",
    title: "",
    titleKey: "experience_cr_espassos_name",
    org: "CR espassos",
    descriptionKey: "experience_cr_espassos_description",
    link: "https://www.linkedin.com/company/cr-espassos/about/",
    techs: ["Revit", "AutoCAD", "Microsoft Office"],
    dateStart: new Date("2022-09"),
    dateEnd: new Date("2023-08"),
    img: "experience/crespassos.jpeg",
  },
  {
    id: "exp-subvisual",
    category: "experience",
    title: "Full-stack Developer",
    org: "Subvisual",
    descriptionKey: "experience_subvisual_description",
    link: "https://subvisual.com/",
    techs: [
      "React",
      "TypeScript",
      "MUI",
      "Solidity",
      "Wagmi",
      "Supabase",
      "PostgreSQL",
      "Git",
      "GitHub",
      "Notion",
      "Blockchain",
      "Web3",
      "Figma",
    ],
    dateStart: new Date("2023-12"),
    dateEnd: new Date("2024-02"),
    img: "experience/subvisual.jpeg",
    featured: true,
  },
  {
    id: "exp-talent-protocol",
    category: "experience",
    title: "Full-stack Developer",
    org: "Talent Protocol",
    descriptionKey: "experience_talent_protocol_description",
    link: "https://www.talentprotocol.com/",
    techs: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript",
      "MUI",
      "HTML",
      "CSS",
      "Supabase",
      "PostgreSQL",
      "Wagmi",
      "Git",
      "GitHub",
      "Notion",
      "Blockchain",
      "Web3",
      "Figma",
    ],
    dateStart: new Date("2024-03"),
    dateEnd: new Date("2025-02"),
    img: "experience/talentprotocol.jpeg",
    featured: true,
  },
  {
    id: "exp-aquasis",
    category: "experience",
    title: "Frontend Developer",
    org: "Aquasis",
    descriptionKey: "experience_aquasis_description",
    link: "https://www.aquasis.pt/",
    techs: [
      "React",
      "TypeScript",
      "JavaScript",
      "Bootstrap",
      "React Native",
      "HTML",
      "CSS",
      "PostgreSQL",
      "Git",
      "GitHub",
    ],
    dateStart: new Date("2025-04"),
    dateEnd: null,
    img: "experience/aquasis.jpeg",
    featured: true,
    status: "ongoing",
  },
];
