import type { ExperienceItem } from "@/types/data";

export const experience: ExperienceItem[] = [
  {
    id: "exp-crespassos",
    category: "experience",
    title: "",
    titleKey: "experience_cr_espassos_name",
    org: "CR espassos",
    descriptionKey: "experience_cr_espassos_description",
    link: "https://www.linkedin.com/company/cr-espassos/about/",
    techs: ["Revit", "AutoCAD", "Microsoft Office"],
    dateStart: new Date("2022-09-01"),
    dateEnd: new Date("2023-08-31"),
    img: "",
    hasDetailsPage: false,
  },
  {
    id: "exp-subvisual",
    category: "experience",
    title: "Full-stack Developer",
    org: "Subvisual",
    descriptionKey: "experience_subvisual_description",
    link: "https://subvisual.com/",
    techs: [
      "React",
      "TypeScript",
      "MUI",
      "Wagmi",
      "Solidity",
      "Supabase",
      "PostgreSQL",
      "Figma",
    ],
    dateStart: new Date("2023-12-01"),
    dateEnd: new Date("2024-02-29"),
    img: "",
    featured: true,
    hasDetailsPage: true,
  },
  {
    id: "exp-talent-protocol",
    category: "experience",
    title: "Full-stack Developer",
    org: "Talent Protocol",
    descriptionKey: "experience_talent_protocol_description",
    link: "https://www.talentprotocol.com/",
    techs: [
      "React",
      "Next.js",
      "TypeScript",
      "MUI",
      "HTML",
      "CSS",
      "Supabase",
      "PostgreSQL",
      "Wagmi",
      "Figma",
    ],
    dateStart: new Date("2024-03-01"),
    dateEnd: new Date("2025-02-28"),
    img: "",
    featured: true,
    hasDetailsPage: true,
  },
  {
    id: "exp-aquasis",
    category: "experience",
    title: "Frontend Developer",
    org: "Aquasis",
    descriptionKey: "experience_aquasis_description",
    link: "https://www.aquasis.pt/",
    techs: [
      "React",
      "React Native",
      "TypeScript",
      "Bootstrap",
      "PostgreSQL",
      "Postman",
    ],
    dateStart: new Date("2025-04-01"),
    dateEnd: null,
    img: "",
    featured: true,
    status: "current",
    hasDetailsPage: false,
  },
];
