import type { DataItem } from "@/types/data";

export const projects: DataItem[] = [
  {
    id: "proj-giraffes",
    category: "projects",
    title: "Giraffes vs Sea",
    org: "",
    subjectKey: "project_giraffes_vs_sea_subject",
    descriptionKey: "project_giraffes_vs_sea_description",
    link: "https://giraffes-vs-sea.netlify.app/",
    techs: ["JavaScript", "HTML", "CSS", "DOM Manipulation"],
    dateStart: new Date("2023-09"),
    status: "completed",
    img: "projects/giraffes-vs-sea.png",
  },
  {
    id: "proj-house-of-legends",
    category: "projects",
    title: "House of Legends",
    org: "",
    link: "https://house-of-legends.netlify.app/",
    techs: ["React", "JavaScript", "CSS", "Node.js", "REST API"],
    dateStart: new Date("2023-10"),
    status: "outdated",
  },
  {
    id: "proj-finace",
    category: "projects",
    title: "FIN/ACE",
    org: "",
    subjectKey: "project_finace_subject",
    descriptionKey: "project_finace_description",
    link: "",
    techs: ["React", "JavaScript", "CSS", "Node.js", "Express.js", "MongoDB"],
    dateStart: new Date("2023-11"),
    dateEnd: new Date("2023-12"),
    status: "inactive",
  },
  {
    id: "proj-finace-v2",
    category: "projects",
    title: "FIN/ACE v2",
    org: "",
    descriptionKey: "project_finace_description",
    link: "https://finace-v2.netlify.app/",
    techs: [
      "React",
      "TypeScript",
      "MUI",
      "Node.js",
      "Express.js",
      "Supabase",
      "PostgreSQL",
    ],
    dateStart: new Date("2024-07"),
    dateEnd: new Date("2024-08"),
    status: "inactive",
  },
  {
    id: "proj-passport",
    category: "projects",
    title: "Passport by Talent Protocol",
    org: "Talent Protocol",
    link: "https://passport.talentprotocol.com/",
    techs: ["React", "TypeScript", "MUI", "Wagmi", "Blockchain"],
    dateStart: new Date("2024-04"),
    dateEnd: new Date("2024-08"),
    status: "completed",
  },
  {
    id: "proj-build",
    category: "projects",
    title: "Build by Talent Protocol",
    org: "Talent Protocol",
    link: "https://build.top/",
    techs: [
      "Next.js",
      "TypeScript",
      "MUI",
      "Wagmi",
      "PostgreSQL",
      "Blockchain",
    ],
    dateStart: new Date("2024-04"),
    dateEnd: new Date("2024-06"),
    status: "completed",
  },
  {
    id: "proj-builderfi",
    category: "projects",
    title: "Builderfi by Talent Protocol",
    org: "Talent Protocol",
    link: "https://mirror.xyz/talentprotocol.eth/dSkw_mNNOgs6GZEjZ3GTJMt0uJ5DjpWGkX3rncF1OD8/",
    techs: ["Next.js", "TypeScript", "MUI", "Wagmi", "Blockchain"],
    dateStart: new Date("2024-04"),
    dateEnd: new Date("2024-08"),
    status: "inactive",
  },
  {
    id: "proj-wordlechain",
    category: "projects",
    title: "Wordlechain",
    org: "Subvisual",
    subjectKey: "project_wordlechain_subject",
    descriptionKey: "project_wordlechain_description",
    link: "https://wordlechain.netlify.app/",
    techs: ["React", "TypeScript", "MUI", "Wagmi", "Solidity", "Blockchain"],
    dateStart: new Date("2023-12"),
    dateEnd: new Date("2024-01"),
    status: "completed",
    featured: true,
    img: "projects/wordlechain.png",
  },
  {
    id: "proj-talentsy",
    category: "projects",
    title: "Talentsy",
    org: "Subvisual",
    subjectKey: "project_talentsy_subject",
    descriptionKey: "project_talentsy_description",
    link: "https://talentsy.netlify.app/",
    techs: ["React", "TypeScript", "MUI", "Supabase", "PostgreSQL"],
    dateStart: new Date("2024-01"),
    dateEnd: new Date("2024-02"),
    status: "outdated",
    featured: true,
    img: "projects/talentsy.png",
  },
  {
    id: "proj-poketracker",
    category: "projects",
    title: "Poketracker",
    org: "",
    subjectKey: "project_poketracker_subject",
    descriptionKey: "project_poketracker_description",
    link: "https://poketracker.netlify.app/",
    techs: [
      "Next.js",
      "TypeScript",
      "Shadcn/UI",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
    ],
    dateStart: new Date("2025-10"),
    dateEnd: null,
    status: "ongoing",
    featured: true,
  },
  {
    id: "proj-uparque",
    category: "projects",
    title: "Uparque",
    org: "",
    subjectKey: "project_uparque_subject",
    descriptionKey: "project_uparque_description",
    link: "https://uparque.netlify.app/",
    techs: ["React", "TypeScript", "MUI", "Node.js", "Express.js", "MongoDB"],
    dateStart: new Date("2026-04"),
    dateEnd: null,
    status: "ongoing",
    featured: true,
  },
];
