import type { ProjectItem } from "@/types/data";

export const projects: ProjectItem[] = [
  {
    id: "proj-giraffes",
    category: "projects",
    title: "Giraffes vs Sea",
    org: "",
    subjectKey: "project_giraffes_vs_sea_subject",
    descriptionKey: "project_giraffes_vs_sea_description",
    link: "https://giraffes-vs-sea.netlify.app/",
    techs: ["JavaScript", "HTML", "CSS", "DOM Manipulation"],
    dateStart: new Date("2023-09-01"),
    status: "completed",
    hasDetailsPage: true,
    images: ["projects/giraffes-vs-sea/giraffes-vs-sea-1.png"],
  },
  {
    id: "proj-house-of-legends",
    category: "projects",
    title: "House of Legends",
    org: "",
    link: "",
    techs: ["React", "JavaScript", "CSS", "Node.js", "REST API"],
    dateStart: new Date("2023-10-01"),
    status: "outdated",
    hasDetailsPage: false,
    images: [],
  },
  {
    id: "proj-finace",
    category: "projects",
    title: "FIN/ACE",
    org: "",
    subjectKey: "project_finace_subject",
    descriptionKey: "project_finace_description",
    link: "",
    techs: ["React", "JavaScript", "CSS", "Node.js", "Express.js", "MongoDB"],
    dateStart: new Date("2023-11-01"),
    dateEnd: new Date("2023-12-20"),
    status: "inactive",
    hasDetailsPage: false,
    images: [],
  },
  {
    id: "proj-finace-v2",
    category: "projects",
    title: "FIN/ACE v2",
    org: "",
    descriptionKey: "project_finace_description",
    link: "",
    techs: [
      "React",
      "TypeScript",
      "MUI",
      "Node.js",
      "Express.js",
      "Supabase",
      "PostgreSQL",
    ],
    dateStart: new Date("2024-07-01"),
    dateEnd: new Date("2024-08-15"),
    status: "inactive",
    hasDetailsPage: false,
    images: [],
  },
  {
    id: "proj-passport",
    category: "projects",
    title: "Passport by Talent Protocol",
    org: "Talent Protocol",
    link: "https://passport.talentprotocol.com/",
    techs: ["React", "TypeScript", "MUI", "Wagmi", "Blockchain"],
    dateStart: new Date("2024-04-01"),
    dateEnd: new Date("2024-08-31"),
    status: "completed",
    hasDetailsPage: false,
    images: [],
  },
  {
    id: "proj-build",
    category: "projects",
    title: "Build by Talent Protocol",
    org: "Talent Protocol",
    link: "https://build.top/",
    techs: [
      "Next.js",
      "TypeScript",
      "MUI",
      "Wagmi",
      "PostgreSQL",
      "Blockchain",
    ],
    dateStart: new Date("2024-04-01"),
    dateEnd: new Date("2024-06-30"),
    status: "completed",
    hasDetailsPage: false,
    images: [],
  },
  {
    id: "proj-builderfi",
    category: "projects",
    title: "Builderfi by Talent Protocol",
    org: "Talent Protocol",
    link: "https://mirror.xyz/talentprotocol.eth/dSkw_mNNOgs6GZEjZ3GTJMt0uJ5DjpWGkX3rncF1OD8/",
    techs: ["Next.js", "TypeScript", "MUI", "Wagmi", "Blockchain"],
    dateStart: new Date("2024-04-01"),
    dateEnd: new Date("2024-08-31"),
    status: "inactive",
    hasDetailsPage: false,
    images: [],
  },
  {
    id: "proj-wordlechain",
    category: "projects",
    title: "Wordlechain",
    org: "Subvisual",
    subjectKey: "project_wordlechain_subject",
    descriptionKey: "project_wordlechain_description",
    link: "https://wordlechain.netlify.app/",
    techs: ["React", "TypeScript", "MUI", "Wagmi", "Solidity", "Blockchain"],
    dateStart: new Date("2023-12-05"),
    dateEnd: new Date("2024-01-25"),
    status: "completed",
    featured: true,
    hasDetailsPage: true,
    images: [
      "projects/wordlechain/wordlechain-1.png",
      "projects/wordlechain/wordlechain-2.png",
      "projects/wordlechain/wordlechain-3.png",
    ],
  },
  {
    id: "proj-talentsy",
    category: "projects",
    title: "Talentsy",
    org: "Subvisual",
    subjectKey: "project_talentsy_subject",
    descriptionKey: "project_talentsy_description",
    link: "",
    techs: ["React", "TypeScript", "MUI", "Supabase", "PostgreSQL"],
    dateStart: new Date("2024-01-01"),
    dateEnd: new Date("2024-02-20"),
    status: "outdated",
    featured: false,
    hasDetailsPage: false,
    images: [],
  },
  {
    id: "proj-poketracker",
    category: "projects",
    title: "Poketracker",
    org: "",
    subjectKey: "project_poketracker_subject",
    descriptionKey: "project_poketracker_description",
    link: "",
    techs: [
      "Next.js",
      "TypeScript",
      "Shadcn/UI",
      "Tailwind CSS",
      "Supabase",
      "PostgreSQL",
    ],
    dateStart: new Date("2025-10-01"),
    dateEnd: null,
    status: "ongoing",
    featured: true,
    hasDetailsPage: true,
    images: [
      "projects/poketracker/poketracker-1.png",
      "projects/poketracker/poketracker-2.png",
      "projects/poketracker/poketracker-3.png",
      "projects/poketracker/poketracker-4.png",
    ],
  },
  {
    id: "proj-uparque",
    category: "projects",
    title: "Uparque",
    org: "",
    subjectKey: "project_uparque_subject",
    descriptionKey: "project_uparque_description",
    link: "",
    techs: ["React", "TypeScript", "MUI", "Node.js", "Express.js", "MongoDB"],
    dateStart: new Date("2026-04-01"),
    dateEnd: null,
    status: "ongoing",
    featured: true,
    hasDetailsPage: false,
    images: [],
  },
];
